<div class="container">
    <h2>Všechny příspěvky:</h2>
    <table class="table">
        <thead>
        <tr>
            <th>id</th>
            <th>Název</th>
            <th>Popis</th>
            <th>Recenzent 1</th>
            <th>Recenzent 2</th>
            <th>Recenzent 3</th>
        </tr>
        </thead>
        <tbody>

        <?php
        foreach ($contributions as $contribution)
        {
            echo "<tr>";
            echo "<td>" .  $contribution->id . "</td>" . PHP_EOL;
            echo "<td>" .  $contribution->title . "</td>" . PHP_EOL;
            echo "<td>" .  $contribution->description . "</td>" . PHP_EOL;
            if($contribution->pocet_recenzentu>0) {
                $recenzentiPole = $contribution->recenzenti;
                foreach ($recenzentiPole as $recenzent) {
                    echo "<td>" . $recenzent->username . "</td>" . PHP_EOL;
                }
            }
            for($it=3-$contribution->pocet_recenzentu; $it>0; $it--)
            {
                echo "<td><form action='#' method='POST'><INPUT TYPE=HIDDEN NAME='priraditID' value='$contribution->id'/><input type='submit' value='Přiřadit'/></form></td>" . PHP_EOL;
            }

            /*
            echo "<td>" .  $contribution->score_lang . "</td>" . PHP_EOL;
            echo "<td>" .  $contribution->score_appearance . "</td>" . PHP_EOL;
            echo "<td>" .  $contribution->score_benefit . "</td>" . PHP_EOL;*/
            echo "</tr>";

        } ?>

        </tbody>
    </table>



</div>