<div class="container">
    <h1>Registrace</h1>
    <form action="#" method="POST" autocomplete="off">
        Uživatelské jméno:<br>
        <input type="text" name="username" placeholder="username"><br>
        Heslo:<br>
        <input type="password" name="password" placeholder="password"><br>
        Heslo znovu (pro kontrolu):<br>
        <input type="password" name="passwordCh" placeholder="password"><br>
        Email:<br>
        <input type="text" name="email" placeholder="email"><br>
        <?php if($_SESSION['registerError']!=""){echo "<font color='red'>" . $_SESSION['registerError'] . "</font>";} ?><br>
        <input type="submit" value="Submit">
    </form>
</div>
