<div class="container">

    <h2>Nahrání souboru:</h2>
    <form action="#" method="post" enctype="multipart/form-data">
        Název:
        <input type="text" name="filename"><br>
        PDF soubor:
        <input type="file" name="fileToUpload" /*id="fileToUpload"*/><br>
        Popis: <input type="text" name="description">
        <input type="submit" value="Upload" name="submit">
    </form>



</div>