<div class="container">
<table class="table">
  <thead>
  <tr>
      <th>Název</th>
      <th>Popis</th>
      <th>Hodnocení - Jazyk</th>
      <th>Hodnocení - Úprava</th>
      <th>Hodnocení - Přínos</th>
      <th>Otevřít</th>
  </tr>
  </thead>
  <tbody>
    <?php
    foreach ($contents as $contribution)
    {
        echo "<tr>";
        echo "<td>" .  $contribution->title . "</td>" . PHP_EOL;
        echo "<td>" .  $contribution->description . "</td>" . PHP_EOL;
        echo "<td>" .  round($contribution->score_lang) . "</td>" . PHP_EOL;
        echo "<td>" .  round($contribution->score_appearance) . "</td>" . PHP_EOL;
        echo "<td>" .  round($contribution->score_benefit) . "</td>" . PHP_EOL;
        if($contribution->file)
        {
            echo "<td><form action='#' method='POST'><INPUT TYPE=HIDDEN NAME='path' value='$contribution->file'/><input type='submit' value='Otevřít'/></form></td>" . PHP_EOL;
        }
        else {
            echo "<td></td>";
        }
        echo "</tr>";

    } ?>

    </tbody>
	</table>

	<br>





</div>
